version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  accountance:
    image: ${DOCKER_REGISTRY-}accountance
    build:
      context: .
      dockerfile: Accountance/Dockerfile

